/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoReportRouteImport } from './routes/seo-report'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as PromptLabRouteImport } from './routes/prompt-lab'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesAiVsTraditionalCadRouteImport } from './routes/resources.ai-vs-traditional-cad'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoReportRoute = SeoReportRouteImport.update({
  id: '/seo-report',
  path: '/seo-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLabRoute = PromptLabRouteImport.update({
  id: '/prompt-lab',
  path: '/prompt-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesAiVsTraditionalCadRoute =
  ResourcesAiVsTraditionalCadRouteImport.update({
    id: '/resources/ai-vs-traditional-cad',
    path: '/resources/ai-vs-traditional-cad',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/prompt-lab': typeof PromptLabRoute
  '/reception': typeof ReceptionRoute
  '/seo-report': typeof SeoReportRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resources/ai-vs-traditional-cad': typeof ResourcesAiVsTraditionalCadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/prompt-lab': typeof PromptLabRoute
  '/reception': typeof ReceptionRoute
  '/seo-report': typeof SeoReportRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resources/ai-vs-traditional-cad': typeof ResourcesAiVsTraditionalCadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/prompt-lab': typeof PromptLabRoute
  '/reception': typeof ReceptionRoute
  '/seo-report': typeof SeoReportRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resources/ai-vs-traditional-cad': typeof ResourcesAiVsTraditionalCadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/history'
    | '/prompt-lab'
    | '/reception'
    | '/seo-report'
    | '/settings'
    | '/sitemap.xml'
    | '/resources/ai-vs-traditional-cad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/history'
    | '/prompt-lab'
    | '/reception'
    | '/seo-report'
    | '/settings'
    | '/sitemap.xml'
    | '/resources/ai-vs-traditional-cad'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/history'
    | '/prompt-lab'
    | '/reception'
    | '/seo-report'
    | '/settings'
    | '/sitemap.xml'
    | '/resources/ai-vs-traditional-cad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HistoryRoute: typeof HistoryRoute
  PromptLabRoute: typeof PromptLabRoute
  ReceptionRoute: typeof ReceptionRoute
  SeoReportRoute: typeof SeoReportRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ResourcesAiVsTraditionalCadRoute: typeof ResourcesAiVsTraditionalCadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-report': {
      id: '/seo-report'
      path: '/seo-report'
      fullPath: '/seo-report'
      preLoaderRoute: typeof SeoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-lab': {
      id: '/prompt-lab'
      path: '/prompt-lab'
      fullPath: '/prompt-lab'
      preLoaderRoute: typeof PromptLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/ai-vs-traditional-cad': {
      id: '/resources/ai-vs-traditional-cad'
      path: '/resources/ai-vs-traditional-cad'
      fullPath: '/resources/ai-vs-traditional-cad'
      preLoaderRoute: typeof ResourcesAiVsTraditionalCadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HistoryRoute: HistoryRoute,
  PromptLabRoute: PromptLabRoute,
  ReceptionRoute: ReceptionRoute,
  SeoReportRoute: SeoReportRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ResourcesAiVsTraditionalCadRoute: ResourcesAiVsTraditionalCadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
